export default [
  {
    type: "function",
    name: "batchWithdraw",
    inputs: [
      { name: "_protocolCodes", type: "uint16[]", internalType: "uint16[]" },
      {
        name: "_markets",
        type: "tuple[]",
        internalType: "struct TezoroLendingLib.Market[]",
        components: [
          { name: "loanToken", type: "address", internalType: "address" },
          { name: "collateralToken", type: "address", internalType: "address" },
          { name: "marketAddress", type: "address", internalType: "address" },
          { name: "auxId", type: "bytes32", internalType: "bytes32" },
          { name: "flags", type: "uint16", internalType: "uint16" },
        ],
      },
      { name: "isClaimRewardsRequired", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "borrow",
    inputs: [
      { name: "protocolCode", type: "uint16", internalType: "uint16" },
      {
        name: "market",
        type: "tuple",
        internalType: "struct TezoroLendingLib.Market",
        components: [
          { name: "loanToken", type: "address", internalType: "address" },
          { name: "collateralToken", type: "address", internalType: "address" },
          { name: "marketAddress", type: "address", internalType: "address" },
          { name: "auxId", type: "bytes32", internalType: "bytes32" },
          { name: "flags", type: "uint16", internalType: "uint16" },
        ],
      },
      { name: "minAmount", type: "uint256", internalType: "uint256" },
      { name: "maxAmount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "currentAllocationNonce",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "deploymentTimestamp",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "distribute",
    inputs: [
      { name: "_tokens", type: "address[]", internalType: "address[]" },
      { name: "_protocolCodes", type: "uint16[]", internalType: "uint16[]" },
      {
        name: "_markets",
        type: "tuple[]",
        internalType: "struct TezoroLendingLib.Market[]",
        components: [
          { name: "loanToken", type: "address", internalType: "address" },
          { name: "collateralToken", type: "address", internalType: "address" },
          { name: "marketAddress", type: "address", internalType: "address" },
          { name: "auxId", type: "bytes32", internalType: "bytes32" },
          { name: "flags", type: "uint16", internalType: "uint16" },
        ],
      },
      { name: "_amounts", type: "uint256[]", internalType: "uint256[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "factory",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getProtocols",
    inputs: [],
    outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "initialize",
    inputs: [
      { name: "_owner", type: "address", internalType: "address" },
      { name: "_lens", type: "address", internalType: "address" },
      { name: "_adapters", type: "address[]", internalType: "address[]" },
      { name: "_factory", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "initialized",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isDisabled",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lastFeeCollected",
    inputs: [
      { name: "", type: "uint16", internalType: "uint16" },
      { name: "", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lens",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pauseProtocol",
    inputs: [{ name: "protocolCode", type: "uint16", internalType: "uint16" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "permanentlyDisable",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "protocolToAdapter",
    inputs: [{ name: "", type: "uint16", internalType: "uint16" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "rebalance",
    inputs: [
      {
        name: "steps",
        type: "tuple[]",
        internalType: "struct TezoroLendingLib.RebalanceStep[]",
        components: [
          {
            name: "fromMarket",
            type: "tuple",
            internalType: "struct TezoroLendingLib.Market",
            components: [
              { name: "loanToken", type: "address", internalType: "address" },
              {
                name: "collateralToken",
                type: "address",
                internalType: "address",
              },
              {
                name: "marketAddress",
                type: "address",
                internalType: "address",
              },
              { name: "auxId", type: "bytes32", internalType: "bytes32" },
              { name: "flags", type: "uint16", internalType: "uint16" },
            ],
          },
          {
            name: "toMarket",
            type: "tuple",
            internalType: "struct TezoroLendingLib.Market",
            components: [
              { name: "loanToken", type: "address", internalType: "address" },
              {
                name: "collateralToken",
                type: "address",
                internalType: "address",
              },
              {
                name: "marketAddress",
                type: "address",
                internalType: "address",
              },
              { name: "auxId", type: "bytes32", internalType: "bytes32" },
              { name: "flags", type: "uint16", internalType: "uint16" },
            ],
          },
          { name: "fromProtocolCode", type: "uint16", internalType: "uint16" },
          { name: "toProtocolCode", type: "uint16", internalType: "uint16" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "recoverERC20",
    inputs: [
      { name: "tokenAddress", type: "address", internalType: "address" },
      { name: "tokenAmount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "repay",
    inputs: [
      { name: "protocolCode", type: "uint16", internalType: "uint16" },
      {
        name: "market",
        type: "tuple",
        internalType: "struct TezoroLendingLib.Market",
        components: [
          { name: "loanToken", type: "address", internalType: "address" },
          { name: "collateralToken", type: "address", internalType: "address" },
          { name: "marketAddress", type: "address", internalType: "address" },
          { name: "auxId", type: "bytes32", internalType: "bytes32" },
          { name: "flags", type: "uint16", internalType: "uint16" },
        ],
      },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  { type: "event", name: "AgentDeactivated", inputs: [], anonymous: false },
  {
    type: "event",
    name: "Borrowed",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "protocolCode",
        type: "uint16",
        indexed: true,
        internalType: "uint16",
      },
      {
        name: "marketId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "onBehalfOf",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "minAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "maxAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ExternalCallFailed",
    inputs: [
      {
        name: "target",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "action",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "reason",
        type: "string",
        indexed: false,
        internalType: "string",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ManagementFeeTaken",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "protocolCode",
        type: "uint16",
        indexed: true,
        internalType: "uint16",
      },
      {
        name: "marketId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "recipient",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "MarketRegistered",
    inputs: [
      {
        name: "protocolCode",
        type: "uint16",
        indexed: true,
        internalType: "uint16",
      },
      {
        name: "marketId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "market",
        type: "tuple",
        indexed: false,
        internalType: "struct TezoroLendingLib.Market",
        components: [
          { name: "loanToken", type: "address", internalType: "address" },
          { name: "collateralToken", type: "address", internalType: "address" },
          { name: "marketAddress", type: "address", internalType: "address" },
          { name: "auxId", type: "bytes32", internalType: "bytes32" },
          { name: "flags", type: "uint16", internalType: "uint16" },
        ],
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProtocolAdapterRegistered",
    inputs: [
      {
        name: "protocolCode",
        type: "uint16",
        indexed: true,
        internalType: "uint16",
      },
      {
        name: "adapter",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProtocolDisabled",
    inputs: [
      {
        name: "protocolCode",
        type: "uint16",
        indexed: true,
        internalType: "uint16",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RebalanceSupplied",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "toProtocol",
        type: "uint16",
        indexed: true,
        internalType: "uint16",
      },
      {
        name: "toMarketId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "allocationNonce",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RebalanceWithdrawn",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "protocolCode",
        type: "uint16",
        indexed: true,
        internalType: "uint16",
      },
      {
        name: "marketId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Repaid",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "protocolCode",
        type: "uint16",
        indexed: true,
        internalType: "uint16",
      },
      {
        name: "marketId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "onBehalfOf",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RewardsClaimed",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "protocolCode",
        type: "uint16",
        indexed: true,
        internalType: "uint16",
      },
      {
        name: "marketId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "recipient",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "rewardToken",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "allocationNonce",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Supplied",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "protocolCode",
        type: "uint16",
        indexed: true,
        internalType: "uint16",
      },
      {
        name: "marketId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "nonce",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Withdrawn",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "protocolCode",
        type: "uint16",
        indexed: true,
        internalType: "uint16",
      },
      {
        name: "marketId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "managementFee",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "nonce",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "AdapterAlreadyRegistered", inputs: [] },
  {
    type: "error",
    name: "AdapterInterfaceNotSupported",
    inputs: [{ name: "adapter", type: "address", internalType: "address" }],
  },
  { type: "error", name: "AgentDisabled", inputs: [] },
  {
    type: "error",
    name: "InsufficientBalance",
    inputs: [
      { name: "expected", type: "uint256", internalType: "uint256" },
      { name: "actual", type: "uint256", internalType: "uint256" },
      { name: "token", type: "address", internalType: "address" },
    ],
  },
  { type: "error", name: "InvalidInitialization", inputs: [] },
  {
    type: "error",
    name: "InvalidParam",
    inputs: [{ name: "reason", type: "string", internalType: "string" }],
  },
  {
    type: "error",
    name: "MarketTokenMismatch",
    inputs: [
      { name: "marketId", type: "bytes32", internalType: "bytes32" },
      { name: "expected", type: "address", internalType: "address" },
      { name: "actual", type: "address", internalType: "address" },
    ],
  },
  { type: "error", name: "MismatchedInputLengths", inputs: [] },
  { type: "error", name: "NoAdapter", inputs: [] },
  { type: "error", name: "NoAdaptersProvided", inputs: [] },
  {
    type: "error",
    name: "NoMarketTokenRegistered",
    inputs: [{ name: "marketId", type: "bytes32", internalType: "bytes32" }],
  },
  { type: "error", name: "NoTokensToWithdraw", inputs: [] },
  { type: "error", name: "NotAuthorized", inputs: [] },
  {
    type: "error",
    name: "ProtocolNotFound",
    inputs: [{ name: "protocolCode", type: "uint16", internalType: "uint16" }],
  },
  {
    type: "error",
    name: "ProtocolPaused",
    inputs: [{ name: "protocolCode", type: "uint16", internalType: "uint16" }],
  },
] as const;
